package infrastructure

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// BlobDriver abstracts byte storage: local disk (dev) or S3 object storage
// (legacy address). Keys are always fully server-generated by the service —
// request input never becomes a path, so traversal is impossible.
type BlobDriver interface {
	// Store writes content under key.
	Store(ctx context.Context, key string, content io.Reader, contentType, originalName string) error
	// Remove deletes stored bytes. Missing keys are not an error.
	Remove(ctx context.Context, key string)
	// URLFor resolves a readable URL (local path or presigned S3 URL).
	URLFor(ctx context.Context, key string) (string, error)
}

// LocalDriver stores bytes under dir, served by Server.MountUploads.
type LocalDriver struct {
	dir string
}

// NewLocalDriver prepares dir for storage.
func NewLocalDriver(dir string) (*LocalDriver, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	return &LocalDriver{dir: dir}, nil
}

// Store writes content to dir/key (parent dirs created).
func (d *LocalDriver) Store(_ context.Context, key string, content io.Reader, _ string, _ string) error {
	full := filepath.Join(d.dir, filepath.FromSlash(key))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	out, err := os.Create(full)
	if err != nil {
		return err
	}
	defer func() { _ = out.Close() }()
	written, err := io.Copy(out, content)
	if err != nil {
		_ = os.Remove(full)
		return err
	}
	if written == 0 {
		_ = os.Remove(full)
		return fmt.Errorf("file kosong")
	}
	return nil
}

// Remove deletes stored bytes. Missing files are not an error.
func (d *LocalDriver) Remove(_ context.Context, key string) {
	_ = os.Remove(filepath.Join(d.dir, filepath.FromSlash(key)))
}

// URLFor returns the public path served under /uploads/.
func (d *LocalDriver) URLFor(_ context.Context, key string) (string, error) {
	return "/uploads/" + key, nil
}
