package infrastructure

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

// S3Driver stores bytes in an S3-compatible bucket (legacy: IDCloudHost
// https://is3.cloudhost.id, bucket mini-erp, path-style). Files stay
// private; reads go through presigned URLs (300 dtk default, warisan).
type S3Driver struct {
	client        *s3.Client
	presign       *s3.PresignClient
	bucket        string
	publicBaseURL string
	ttl           time.Duration
}

// S3Config carries the object-storage settings (see config.Storage).
type S3Config struct {
	Endpoint        string
	Bucket          string
	Region          string
	ForcePathStyle  bool
	AccessKeyID     string
	SecretAccessKey string
	PublicBaseURL   string
	SignedURLTTLS   time.Duration
}

// NewS3Driver builds the bucket client. Bucket + keys are validated by the
// composition root (config.Load) before this runs.
func NewS3Driver(cfg S3Config) *S3Driver {
	client := s3.New(s3.Options{
		Region: cfg.Region,
		Credentials: aws.NewCredentialsCache(credentials.NewStaticCredentialsProvider(
			cfg.AccessKeyID, cfg.SecretAccessKey, "")),
		BaseEndpoint: aws.String(cfg.Endpoint),
		UsePathStyle: cfg.ForcePathStyle,
		DefaultsMode: aws.DefaultsModeStandard,
	})
	return &S3Driver{
		client: client, presign: s3.NewPresignClient(client),
		bucket: cfg.Bucket, publicBaseURL: cfg.PublicBaseURL, ttl: cfg.SignedURLTTLS,
	}
}

// Store puts one object. Keys are always server-generated by the service.
func (d *S3Driver) Store(ctx context.Context, key string, content io.Reader, contentType, originalName string) error {
	meta := map[string]string{}
	if originalName = strings.TrimSpace(originalName); originalName != "" {
		if len(originalName) > 255 {
			originalName = originalName[:255]
		}
		meta["original_name"] = originalName
	}
	_, err := d.client.PutObject(ctx, &s3.PutObjectInput{
		Bucket: aws.String(d.bucket), Key: aws.String(key),
		Body: content, ContentType: aws.String(contentType), Metadata: meta,
	})
	return err
}

// Remove deletes one object. Missing keys are not an error (best-effort,
// same semantics as the local driver).
func (d *S3Driver) Remove(ctx context.Context, key string) {
	_, _ = d.client.DeleteObject(ctx, &s3.DeleteObjectInput{
		Bucket: aws.String(d.bucket), Key: aws.String(key),
	})
}

// URLFor resolves a public URL when configured, else a presigned GET.
func (d *S3Driver) URLFor(ctx context.Context, key string) (string, error) {
	if d.publicBaseURL != "" {
		return d.publicBaseURL + "/" + key, nil
	}
	out, err := d.presign.PresignGetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(d.bucket), Key: aws.String(key),
	}, s3.WithPresignExpires(d.ttl))
	if err != nil {
		return "", fmt.Errorf("gagal membuat URL berkas: %w", err)
	}
	return out.URL, nil
}
